/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus dependency status. Always 200 so the API stays up while deps recover.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description Games on a date (US Eastern; default today) with their latest pre-game prediction.
         */
        get: operations["list_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description The model behind current predictions: backtest vs Elo, calibration, importance.
         */
        get: operations["get_model_api_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/winprob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Winprob
         * @description Every in-game win-probability point recorded for the game (empty before tip-off).
         */
        get: operations["get_winprob_api_games__game_id__winprob_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/monitoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monitoring
         * @description Latest accuracy check per model and window (pre-game first; season before 30 days).
         */
        get: operations["get_monitoring_api_model_monitoring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparisonRow */
        ComparisonRow: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Home */
            home: number | null;
            /** Away */
            away: number | null;
            /** Higher Is Better */
            higher_is_better: boolean;
        };
        /** EloPoint */
        EloPoint: {
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Season */
            season: number;
            /** Elo */
            elo: number;
        };
        /** Factor */
        Factor: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Contribution */
            contribution: number;
            /**
             * Favors
             * @enum {string}
             */
            favors: "home" | "away";
        };
        /** FeatureImportance */
        FeatureImportance: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Share */
            share: number;
        };
        /** GameDetail */
        GameDetail: {
            /** Game Id */
            game_id: string;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Tip Time Utc */
            tip_time_utc: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "live" | "final";
            /** Season */
            season: number;
            /**
             * Season Type
             * @enum {string}
             */
            season_type: "regular" | "playoffs" | "playin";
            /** Is Neutral */
            is_neutral: boolean;
            home: components["schemas"]["TeamRef"];
            away: components["schemas"]["TeamRef"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            prediction: components["schemas"]["PredictionSummary"] | null;
            live?: components["schemas"]["LiveSummary"] | null;
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /** Comparison */
            comparison: components["schemas"]["ComparisonRow"][];
        };
        /** GameSummary */
        GameSummary: {
            /** Game Id */
            game_id: string;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Tip Time Utc */
            tip_time_utc: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "live" | "final";
            /** Season */
            season: number;
            /**
             * Season Type
             * @enum {string}
             */
            season_type: "regular" | "playoffs" | "playin";
            /** Is Neutral */
            is_neutral: boolean;
            home: components["schemas"]["TeamRef"];
            away: components["schemas"]["TeamRef"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            prediction: components["schemas"]["PredictionSummary"] | null;
            live?: components["schemas"]["LiveSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /** JobStatus */
        JobStatus: {
            /** Job */
            job: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "success" | "failed";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Detail */
            detail: string | null;
        };
        /** LiveSummary */
        LiveSummary: {
            /** Home Win Prob */
            home_win_prob: number;
            /** Period */
            period: number;
            /** Clock Seconds */
            clock_seconds: number;
            /** Score Home */
            score_home: number;
            /** Score Away */
            score_away: number;
        };
        /** Metrics */
        Metrics: {
            /** Logloss */
            logloss: number;
            /** Brier */
            brier: number;
            /** Accuracy */
            accuracy: number;
            /** Ece */
            ece: number;
            /** N */
            n: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Version */
            version: string;
            /** Run Id */
            run_id: string;
            /** Feature Version */
            feature_version: string;
            /** Calibration */
            calibration: string;
            /** Train Seasons */
            train_seasons: string;
            /**
             * First Used At
             * Format: date-time
             */
            first_used_at: string;
            /** Seasons */
            seasons: components["schemas"]["SeasonMetrics"][];
            pooled_model: components["schemas"]["Metrics"];
            pooled_elo: components["schemas"]["Metrics"];
            /** Reliability */
            reliability: components["schemas"]["ReliabilityBin"][];
            /** Acceptance */
            acceptance: {
                [key: string]: boolean;
            };
            /** Top Features */
            top_features: components["schemas"]["FeatureImportance"][];
        };
        /** MonitoringResult */
        MonitoringResult: {
            /**
             * Model
             * @enum {string}
             */
            model: "pregame" | "ingame";
            /**
             * Window
             * @enum {string}
             */
            window: "season" | "last_30_days";
            /** Model Version */
            model_version: string | null;
            /** Games */
            games: number;
            metrics: components["schemas"]["Metrics"] | null;
            /** Expected Logloss */
            expected_logloss: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "insufficient";
            /** Message */
            message: string;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
        };
        /** PredictionSummary */
        PredictionSummary: {
            /** Home Win Prob */
            home_win_prob: number;
            /** Model Version */
            model_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Made Before Tip */
            made_before_tip: boolean;
        };
        /** ReliabilityBin */
        ReliabilityBin: {
            /** Bin Low */
            bin_low: number;
            /** Bin High */
            bin_high: number;
            /** Mean Pred */
            mean_pred: number;
            /** Observed */
            observed: number;
            /** Count */
            count: number;
        };
        /** SeasonMetrics */
        SeasonMetrics: {
            /** Season */
            season: number;
            model: components["schemas"]["Metrics"];
            elo: components["schemas"]["Metrics"];
        };
        /** Slate */
        Slate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Prev Date */
            prev_date: string | null;
            /** Next Date */
            next_date: string | null;
            /** Games */
            games: components["schemas"]["GameSummary"][];
        };
        /** SystemStatus */
        SystemStatus: {
            /** Models */
            models: {
                [key: string]: string | null;
            };
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Monitoring */
            monitoring: components["schemas"]["MonitoringResult"][];
        };
        /** TeamDetail */
        TeamDetail: {
            team: components["schemas"]["TeamRef"];
            /** Elo */
            elo: number | null;
            /** Elo History */
            elo_history: components["schemas"]["EloPoint"][];
            /** Recent */
            recent: components["schemas"]["TeamGame"][];
            /** Upcoming */
            upcoming: components["schemas"]["TeamGame"][];
        };
        /** TeamGame */
        TeamGame: {
            /** Game Id */
            game_id: string;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "live" | "final";
            /** Is Home */
            is_home: boolean;
            opponent: components["schemas"]["TeamRef"];
            /** Team Score */
            team_score: number | null;
            /** Opponent Score */
            opponent_score: number | null;
            /** Win Prob */
            win_prob: number | null;
        };
        /** TeamListItem */
        TeamListItem: {
            /** Team Id */
            team_id: number;
            /** Abbreviation */
            abbreviation: string;
            /** City */
            city: string;
            /** Nickname */
            nickname: string;
            /** Full Name */
            full_name: string;
            /** Elo */
            elo: number | null;
        };
        /** TeamRef */
        TeamRef: {
            /** Team Id */
            team_id: number;
            /** Abbreviation */
            abbreviation: string;
            /** City */
            city: string;
            /** Nickname */
            nickname: string;
            /** Full Name */
            full_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WinProbPoint */
        WinProbPoint: {
            /** Action Id */
            action_id: number;
            /** Period */
            period: number;
            /** Clock Seconds */
            clock_seconds: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Score Home */
            score_home: number;
            /** Score Away */
            score_away: number;
            /** Possession */
            possession: number;
            /** Home Win Prob */
            home_win_prob: number;
            /** Description */
            description: string | null;
        };
        /** WinProbSeries */
        WinProbSeries: {
            /** Game Id */
            game_id: string;
            /** Source */
            source: ("live" | "replay") | null;
            /** Model Version */
            model_version: string | null;
            /** Points */
            points: components["schemas"]["WinProbPoint"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListItem"][];
                };
            };
        };
    };
    get_team_api_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
        };
    };
    get_winprob_api_games__game_id__winprob_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WinProbSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monitoring_api_model_monitoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringResult"][];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
