"""raw and core tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 23:15:52.199001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("team_id", name=op.f("pk_teams")),
        schema="core",
    )
    op.create_table(
        "api_responses",
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_gz", sa.LargeBinary(), nullable=False),
        sa.Column("payload_bytes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("request_key", name=op.f("pk_api_responses")),
        schema="raw",
    )
    op.create_index(
        op.f("ix_raw_api_responses_endpoint"),
        "api_responses",
        ["endpoint"],
        unique=False,
        schema="raw",
    )
    # Payloads are already gzipped; skip TOAST's second compression pass.
    op.execute("ALTER TABLE raw.api_responses ALTER COLUMN payload_gz SET STORAGE EXTERNAL")
    op.create_table(
        "ingestion_runs",
        sa.Column("task_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_key", name=op.f("pk_ingestion_runs")),
        schema="raw",
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("season_type", sa.Text(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("tip_time_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.Column("is_neutral", sa.Boolean(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["core.teams.team_id"], name=op.f("fk_games_away_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["core.teams.team_id"], name=op.f("fk_games_home_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("game_id", name=op.f("pk_games")),
        schema="core",
    )
    op.create_index(
        op.f("ix_core_games_game_date"), "games", ["game_date"], unique=False, schema="core"
    )
    op.create_index(op.f("ix_core_games_season"), "games", ["season"], unique=False, schema="core")
    op.create_table(
        "pbp_events",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("action_number", sa.Integer(), nullable=False),
        sa.Column("period", sa.SmallInteger(), nullable=False),
        sa.Column("clock_seconds", sa.Float(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("person_id", sa.BigInteger(), nullable=True),
        sa.Column("action_type", sa.Text(), nullable=True),
        sa.Column("sub_type", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_field_goal", sa.Boolean(), nullable=False),
        sa.Column("shot_value", sa.SmallInteger(), nullable=True),
        sa.Column("shot_result", sa.Text(), nullable=True),
        sa.Column("score_home", sa.SmallInteger(), nullable=False),
        sa.Column("score_away", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_pbp_events_game_id_games")
        ),
        sa.PrimaryKeyConstraint("game_id", "action_id", name=op.f("pk_pbp_events")),
        schema="core",
    )
    op.create_index(
        "ix_pbp_events_game_order",
        "pbp_events",
        ["game_id", "period", "action_number"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "team_game_stats",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("minutes", sa.SmallInteger(), nullable=False),
        sa.Column("pts", sa.SmallInteger(), nullable=False),
        sa.Column("fgm", sa.SmallInteger(), nullable=False),
        sa.Column("fga", sa.SmallInteger(), nullable=False),
        sa.Column("fg3m", sa.SmallInteger(), nullable=False),
        sa.Column("fg3a", sa.SmallInteger(), nullable=False),
        sa.Column("ftm", sa.SmallInteger(), nullable=False),
        sa.Column("fta", sa.SmallInteger(), nullable=False),
        sa.Column("oreb", sa.SmallInteger(), nullable=False),
        sa.Column("dreb", sa.SmallInteger(), nullable=False),
        sa.Column("reb", sa.SmallInteger(), nullable=False),
        sa.Column("ast", sa.SmallInteger(), nullable=False),
        sa.Column("stl", sa.SmallInteger(), nullable=False),
        sa.Column("blk", sa.SmallInteger(), nullable=False),
        sa.Column("tov", sa.SmallInteger(), nullable=False),
        sa.Column("pf", sa.SmallInteger(), nullable=False),
        sa.Column("plus_minus", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_team_game_stats_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["core.teams.team_id"], name=op.f("fk_team_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("game_id", "team_id", name=op.f("pk_team_game_stats")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_game_stats", schema="core")
    op.drop_index("ix_pbp_events_game_order", table_name="pbp_events", schema="core")
    op.drop_table("pbp_events", schema="core")
    op.drop_index(op.f("ix_core_games_season"), table_name="games", schema="core")
    op.drop_index(op.f("ix_core_games_game_date"), table_name="games", schema="core")
    op.drop_table("games", schema="core")
    op.drop_table("ingestion_runs", schema="raw")
    op.drop_index(op.f("ix_raw_api_responses_endpoint"), table_name="api_responses", schema="raw")
    op.drop_table("api_responses", schema="raw")
    op.drop_table("teams", schema="core")
    # ### end Alembic commands ###
