"""features tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 23:41:49.269160
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elo_ratings",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("elo_pre", sa.Float(), nullable=False),
        sa.Column("elo_post", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_elo_ratings_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["core.teams.team_id"], name=op.f("fk_elo_ratings_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("game_id", "team_id", name=op.f("pk_elo_ratings")),
        schema="features",
    )
    op.create_index(
        "ix_elo_ratings_team_date",
        "elo_ratings",
        ["team_id", "game_date"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "game_features",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("feature_version", sa.Text(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "built_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_game_features_game_id_games")
        ),
        sa.PrimaryKeyConstraint("game_id", name=op.f("pk_game_features")),
        schema="features",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_features", schema="features")
    op.drop_index("ix_elo_ratings_team_date", table_name="elo_ratings", schema="features")
    op.drop_table("elo_ratings", schema="features")
    # ### end Alembic commands ###
