"""serving tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 00:05:08.942536
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_versions",
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("feature_version", sa.Text(), nullable=False),
        sa.Column("calibration", sa.Text(), nullable=False),
        sa.Column("train_seasons", sa.Text(), nullable=False),
        sa.Column("backtest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("importance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "first_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_model_versions")),
        schema="serving",
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("feature_version", sa.Text(), nullable=False),
        sa.Column("home_win_prob", sa.Float(), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("made_before_tip", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_predictions_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["serving.model_versions.version"],
            name=op.f("fk_predictions_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        schema="serving",
    )
    op.create_index(
        "ix_predictions_game_created",
        "predictions",
        ["game_id", "created_at"],
        unique=False,
        schema="serving",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_game_created", table_name="predictions", schema="serving")
    op.drop_table("predictions", schema="serving")
    op.drop_table("model_versions", schema="serving")
    # ### end Alembic commands ###
