"""live win probability snapshots

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-07 00:49:33.173165
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_wp_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.SmallInteger(), nullable=False),
        sa.Column("clock_seconds", sa.Float(), nullable=False),
        sa.Column("elapsed_seconds", sa.Float(), nullable=False),
        sa.Column("score_home", sa.SmallInteger(), nullable=False),
        sa.Column("score_away", sa.SmallInteger(), nullable=False),
        sa.Column("possession", sa.SmallInteger(), nullable=False),
        sa.Column("home_win_prob", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["core.games.game_id"], name=op.f("fk_live_wp_snapshots_game_id_games")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_wp_snapshots")),
        schema="serving",
    )
    op.create_index(
        "ix_live_wp_snapshots_game_action",
        "live_wp_snapshots",
        ["game_id", "action_id"],
        unique=False,
        schema="serving",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_live_wp_snapshots_game_action", table_name="live_wp_snapshots", schema="serving"
    )
    op.drop_table("live_wp_snapshots", schema="serving")
    # ### end Alembic commands ###
