"""Drop the misleading pbp action_number index; team_id is an NBA id, not a SERIAL.

Play-by-play order is (game_id, action_id), already covered by the primary key.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 23:34:46.219074
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pbp_events_game_order"), table_name="pbp_events", schema="core")
    # ### end Alembic commands ###
    op.execute("ALTER TABLE core.teams ALTER COLUMN team_id DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS core.teams_team_id_seq")


def downgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS core.teams_team_id_seq OWNED BY core.teams.team_id")
    op.execute(
        "ALTER TABLE core.teams ALTER COLUMN team_id SET DEFAULT nextval('core.teams_team_id_seq')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_pbp_events_game_order"),
        "pbp_events",
        ["game_id", "period", "action_number"],
        unique=False,
        schema="core",
    )
    # ### end Alembic commands ###
